name: go_auth_client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  reactive_forms: ^14.1.0
  http: ^1.3.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  rxdart: ^0.28.0
  http_status_code: ^0.0.2
  custom_sliding_segmented_control: ^1.8.5
  pretty_animated_buttons: ^0.0.2
  quickalert: ^1.1.0
  animated_visibility: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true