name: go_auth_client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  reactive_forms: ^15.0.0
  http: ^1.3.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  rxdart: ^0.28.0
  http_status_code: ^0.0.2
  custom_sliding_segmented_control: ^1.8.5
  pretty_animated_buttons: ^0.0.2
  quickalert: ^1.1.0
  animated_visibility: ^0.0.4
  go_router: ^14.8.1
  password_strength_checker: ^1.2.4
  introduction_screen: ^3.1.17
  bloc: ^9.0.0
  password_complexity:
    path: ../flutter/password_complexity
  flutter_translate: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/i18n/